Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x17e76ef70>
Traceback (most recent call last):
  File "/Users/innocentchikwanda/miniconda3/envs/d2l/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1604, in __del__
    self._shutdown_workers()
  File "/Users/innocentchikwanda/miniconda3/envs/d2l/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1568, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/Users/innocentchikwanda/miniconda3/envs/d2l/lib/python3.9/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/Users/innocentchikwanda/miniconda3/envs/d2l/lib/python3.9/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
  File "/Users/innocentchikwanda/miniconda3/envs/d2l/lib/python3.9/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/Users/innocentchikwanda/miniconda3/envs/d2l/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
